### ISSUE TITLE
UnicodeDecodeError on generating WFP for a text file containing non-UTF-8 characters

### ISSUE THREAD

**Issue by george-kuanli-peng** [scanoss/scanner.py#13]
- ScanOss version: ed0fed8
- Python version: 3.8.5
- Steps to reproduce the bug:
  1. Extract [test.zip](https://github.com/scanoss/scanner.py/files/5596036/test.zip) to a directory, say AAA.<br>
      AAA contains a file named "test.cs" (with a non-UTF-8 character).
  1. Run scanner with `./scanner.py --output scanner-out.txt --format plain AAA/`
- Expected results:
   - A scan result file is produced.
- Actual results:

```
Traceback (most recent call last):
  File "./scanner.py", line 428, in <module>
    main()
  File "./scanner.py", line 108, in main
    scan_folder(args.scan_dir, api_key, scantype, sbom_path, args.format)
  File "./scanner.py", line 151, in scan_folder
    wfp += wfp_for_file(file, path)
  File "./scanner.py", line 359, in wfp_for_file
    if is_binary(path) or skip_snippets(contents.decode(), file):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 7: invalid start byte
```

**Comment by scanossjs** [comment]
Good find! Thank you for reporting this issue. We are looking into it

**Comment by scanossjs** [comment]
Fixed in https://github.com/scanoss/scanner.py/commit/cd1c9c827aceffa431557df854a82bfc08398a0a
