### ISSUE TITLE
"The SCANOSS API returned an invalid JSON" when the scan result format is spdx

### ISSUE THREAD

**Issue by george-kuanli-peng** [scanoss/scanner.py#14]
- ScanOss version: ed0fed8
- Python version: 3.8.5

For the same scanning directory, scanner.py prints "**Scan finished successfully**" when the scan result format is either **plain** or **cyclinedx**, but it prints "**The SCANOSS API returned an invalid JSON**" when the format is **spdx**.

WFP: [scan.wfp.zip](https://github.com/scanoss/scanner.py/files/5601592/scan.wfp.zip)

Scan result returned: [scan-result.zip](https://github.com/scanoss/scanner.py/files/5601643/scan-result.zip)

**Comment by scanossjs** [comment]
Thanks for reporting it, we're checking since it seems like an issue of the engine.

**Comment by scanossjs** [comment]
This was fixed by https://github.com/scanoss/engine/commit/eb1025c4b8a28a26f3e33a5d9cf8295b43f5567d
