### ISSUE TITLE
How do I understand these indicators

### ISSUE THREAD

**Issue by ThierryHenry1994** [scanoss/scanner.py#17]
![image](https://user-images.githubusercontent.com/32047768/116224976-da4d8580-a783-11eb-926f-59ba62c07eae.png)
like the pic showing, I don't know how to understand these indicators .Could you please help me to explain the corresponding meaning. By the way, I saw on your website whether or not the Python script can be done graphically.

thank you very much

**Comment by mscasso-scanoss** [comment]
Hi @ThierryHenry1994 , sorry for the delay. The indicators that you have marked are indicating that the match to your source code is type snippet (so a fragment of it was found in the oss database). The oss_lines are indicating the lines of the file in the database that are matching with the yours one.
Please, let me know if a can help you with something else.
