### ISSUE TITLE
scanner produce invalid json file randomly

### ISSUE THREAD

**Issue by ethan-ic** [scanoss/scanner.py#18]
### Descritpion

When scanning multiple directories using scanner, scanner produced invalid json files for some directories.
Those directories are random.

Take [`go`](https://github.com/golang/go) for example.
When scanner produces invalid json. The tail of this json is
```
        "server": {
            "hostname": "p9",
            "version": "4.1.7",
            "flags": "0",
            "elapsed": "0.003323s"
        }
    }
],

}
```

scan again.
json file become valid, and the tail of this json is
```
        "server": {
            "hostname": "p9",
            "version": "4.1.7",
            "flags": "0",
            "elapsed": "0.677487s"
        }
    }
]
}
```
When [`go`](https://github.com/golang/go) has vaild json in this scan, another directory, [`CompactGUI`](https://github.com/ImminentFate/CompactGUI), whose json become invaild.
However, the [`CompactGUI`](https://github.com/ImminentFate/CompactGUI) had valid json in previous scan.

This issue happens randomly.

**Comment by mscasso-scanoss** [comment]
Hi @ethan-ic Thank you foe report it, we going to work in it ASAP.
