### ISSUE TITLE
CycloneDX BOM Support - XML Format

### ISSUE THREAD

**Issue by ufkesba** [scanoss/scanner.py#9]
This project currently only supports the JSON format for BOM generation.  CycloneDX BOM's come in both XML and JSON, and XML is needed over JSON to upload the BOM to some applications (such as OWASP Dependency Track).

It would be nice to have support for this!

Thanks,
Brent

**Comment by scanossjs** [comment]
We've recently added support for SPDX XML file, but we don't have plans to support CycloneDX XML for the moment.
